#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title: "Winter 2025 ENGR131: Introduction to Programming for Engineers" # The title of the book
author: Joshua C. Agar # The author of the book
copyright: "2025" # Copyright year to be placed in the footer
logo: ./_static/m3-logo.png # A path to the book logo for light mode

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: 800
  only_build_toc_files: true
#   execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

only_build_toc_files: true

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/DrexelEngineering/ENGR131W25 # Online location of your book
  path_to_book: jupyterbook # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  announcement: "Final Exam: Monday, March 17th, 2025, 1-3 PM @ Main Auditorium"
  use_issues_button: true
  use_repository_button: true
  static_path:
    - _static
  css:
    - theme.css
  logo:

# Adds colab button to book
launch_buttons:
  colab: true
  # thebe: true